CREATE TABLE Gitcommit(CommitId INTEGER PRIMARY KEY ASC, timestemp Date, Message VARCHAR(200), UserId INTEGER,  FOREIGN KEY(UserId) REFERENCES Contributor(UserID));
CREATE TABLE Contributor(UserId INTEGER PRIMARY KEY ASC, Name STRING, NumberOfCommits TEXT);
CREATE TABLE FileVersion(FileVersionId INTEGER PRIMARY KEY ASC, Name TEXT, LOC INTEGER, CommitId INTEGER, FOREIGN KEY(CommitId) REFERENCES Gitcommit(CommitId));
CREATE TABLE Skill(SkillId  INTEGER PRIMARY KEY ASC, Name TEXT, Experience INTEGER, FileVersionID INTEGER, FOREIGN KEY(FileVersionId) REFERENCES FileVersion(FileVersionId));

/*CREATE TABLE SkillToFile(ID INTEGER PRIMARY KEY ASC, SkillId INTEGER, FileId INTEGER, FOREIGN KEY(SkillId) REFERENCES Skill(SkilId), FOREIGN KEY(FileId) REFERENCES File(FileId));*/
/*CREATE TABLE FileToCommit(ID INTEGER PRIMARY KEY ASC, CommitId INTEGER, FileId INTEGER, FOREIGN KEY(CommitId) REFERENCES Gitcommit(CommitId), FOREIGN KEY(FileId) REFERENCES File(FileId));*/

